<?php
define('TAG_SET', [
	[
		'foodporn'=>25,
		'instafood'=>20,
		'discoverhongkong'=>10,
		'香港美食'=>10,
		'hkcafe'=>8,
		'hkinfluencer'=>8,
		'抵食'=>8,
		'hkstaycation'=>5,
		'hknightlife'=>5,
	],
	[
		'hkfoodie'=>25,
		'foodiehk'=>20,
		'hkeats'=>15,
		'hkfood'=>15,
		'hongkong'=>15,
		'香港好去處'=>10,
		'hktravel'=>8,
		//'hkhotel'=>8,
		'hkkol'=>8,
		'hkblogger'=>8,
	],
	[
		'黃店'=>25,
		'香港人'=>20,
		'hongkong'=>20,
		'hongkonger'=>15,
		'文宣'=>15,
		'bno'=>10,
		'homekong'=>15,
		'hkfoodie'=>8,
		'香港加油'=>15,
		'香港好去處'=>8,
		'黃色經濟圈'=>8,
		'hkfood'=>8,
		'hkblogger'=>8,
	],
	[
		'hkfoodie'=>20,
		'foodporn'=>20,
		'foodiehk'=>15,
		'instafood'=>15,
		'hkeats'=>10,
		'hkfood'=>10,
		'香港美食'=>8,
		'hkcafe'=>8,
		'抵食'=>8,
		'hkkol'=>5,
		'hkblogger'=>5,
		'hkbeauty'=>5,
		'hkinfluencer'=>5,
		'hklifestyle'=>5,
		'hkpr'=>5,
		'台灣美食'=>5,
	],
	[
		//'hkfoodie'=>15,
		'foodiehk'=>15,
		//'hkcafe'=>8,
		'codinglife'=>15,
		//'hkgirl'=>15,
		'foodporn'=>15,
		'photography'=>15,
		'photooftheday'=>15,
		//'hkeats'=>15,
		'coder'=>15,
		'codingmemes'=>15,
		'investment'=>10,
		//'hklifestyle'=>10,
		'programming'=>10,
		'startup'=>10,
		'hkyoga'=>3,
		//'startuphk'=>5,
		//'hkmarketing'=>5,
		//'香港好去處'=>10,
		'hkstaycation'=>5,
		'hktravel'=>2,
		'hkmarketing'=>2,
		//'hkhotel'=>5,
		'blogger'=>3,
		'山系女孩'=>2,
		'文青'=>2,
		//'hkpr'=>5,
		//'hkbusiness'=>5,
		//'投資'=>5,
		//'買樓'=>5,
	],
	[
		'hkfoodie'=>35,
		'foodiehk'=>30,
		'foodporn'=>15,
		'foodstagram'=>15,
		'likeforlike'=>15,
		'followforfollowback'=>15,
		'foodoftheday'=>15,
		'hkrestaurant'=>20,
		'hkfood'=>20,
		//'hongkong'=>10,
		'indianfood'=>10,
		'hkeats'=>10,
		'香港美食'=>10,
		//'instafood'=>10,
		//'hklifestyle'=>10,
		//'discoverhongkong'=>10,
		'台灣美食'=>5,
		'hkkol'=>5,
		'hkblogger'=>5,
		'hkcafe'=>5,
		'hongkonger'=>5,
		'hongkong'=>5,
		//'香港好去處'=>5,
		'852girl'=>5,
		'hkinfluencer'=>5,
	],
	[
		'photography'=>3,
		'photographer'=>3,
		'photooftheday'=>3,
		'hongkonggirl'=>2,
		'girl'=>3,
		'portraitphotography'=>3,
		'yoga'=>3,
		'poledance'=>1,
		'dance'=>1,
		'blogger'=>2,
		//'hkmodel'=>3,
		'女性'=>1,
		'自撮り'=>2,
		//'瑜伽'=>1,
		'ootd'=>3,
		'sonyalpha'=>3,
		'写真好きな人と繋がりたい'=>1,
		//'私影'=>3,
		//'約拍'=>2,
		//'旗袍寫真'=>1,
		//'文青'=>1,
		//'hkkol'=>1,
		//'hkyoga'=>1,
		//'hkgirl'=>3,
		//'hkpoledance'=>1,
		//'hkdance'=>1,
		//'私影合作'=>1,
		//'私影model'=>1,
		//'hkphotography'=>2,
		//'beautyblogger'=>1,
		//'hkbeauty'=>1,
		//'hkblogger'=>2,
		//'852girl'=>2,
		//'homekong'=>1,
		//'hktravel'=>2,
		//'刺青女孩'=>1,
		//'運動女孩'=>3,
		'山系女孩'=>1,
		//'行山'=>1,
	],
	[
		'hkfoodie'=>35,
		'foodiehk'=>30,
		'foodporn'=>15,
		'hkfoodblogger'=>10,
		'hkfood'=>20,
		//'hongkong'=>10,
		'hkeats'=>10,
		'香港美食'=>10,
		//'instafood'=>10,
		'hklifestyle'=>10,
		'hkkol'=>5,
		'hkblogger'=>5,
		'hkcafe'=>5,
		'香港好去處'=>5,
	],
	[
		'investment'=>5,
		'投資'=>3,
		'炒股'=>3,
		'香港'=>5,
		'科技'=>3,
		'買樓'=>3,
		'blogger'=>4,
		'programming'=>4,
		'developer'=>4,
		'followforfollowback'=>3,
		'likeforlike'=>3,
		'realestate'=>3,
		'entrepreneours'=>3,
		'personalfinance'=>3,
	],
]);
define('COMMENT_SET', [
	['Good one!', 'Jeng Jeng', '想試', '唔錯唔錯', '好吸引！', '影得靚呀', '正呀喂', '高質', '高汁', 'Looks so gooood!', 'My favorite', 'Ho Jeng', '唔錯喎', '吸引牙', '影得咁靚','Bookmark定先','謝謝你的介紹，拍攝手法很好👍，被你的post吸引了，我會繼續留意你的介紹，希望互相學習互相切磋一下🙏🙏🙏☺️☺️☺️👏👏👏'],
	['Jeng~~', '想試', 'so nice', '吸引！', '想要', '影得靚', '正正子', '掂呀！'],
	['support', ' '],
	['Nice!', 'Good one!', '唔錯!', 'Bookmark定先', 'JENG', '高質', '高汁', 'Support', ' ', '多謝分享'],
]);
define('USER_SET', json_decode(file_get_contents(__DIR__."/credentials.json"), true));

define('LOGIN_SET', [
	0=>[
		'user'=>USER_SET['fm.feed'],
		'numberOfLikes'=> 30, 'allowComment'=>true, 'allowLike'=>true,
		'tagsDay'=>TAG_SET[5], 'tagsNight'=>TAG_SET[5],
		'defaultComments'=>COMMENT_SET[0],
		'sleepTimeDay'=>35,
		'sleepTimeNight'=>40,
	],
	1=>[
		'master'=>[
			'user'=>USER_SET['dr.food.hk'],
			'numberOfLikes'=> 30, 'allowComment'=>false, 'allowLike'=>true, 
			'tagsDay'=>TAG_SET[3], 'tagsNight'=>TAG_SET[3],
			'defaultComments'=>COMMENT_SET[1],
		],
		'slave'=>[
			'user'=>USER_SET['hkcoder'],
			'numberOfLikes'=> 50, 'allowComment'=>false, 'allowLike'=>true,
			'tagsDay'=>TAG_SET[2], 'tagsNight'=>TAG_SET[2],
			'defaultComments'=>COMMENT_SET[2],
		],
		'sleepTimeDay'=>40,
		'sleepTimeNight'=>45,
	],
	2=>[
		'master'=>[
			'user'=>USER_SET['fmchan'],
			'numberOfLikes'=> 30, 'allowComment'=>false, 'allowLike'=>true,
			'tagsDay'=>TAG_SET[4], 'tagsNight'=>TAG_SET[4],
			'defaultComments'=>COMMENT_SET[0],
		],
		'slave'=>[
			'user'=>USER_SET['dr.food.hk'],
			'numberOfLikes'=> 70, 'allowComment'=>true, 'allowLike'=>true, 
			'tagsDay'=>TAG_SET[3], 'tagsNight'=>TAG_SET[3],
			'defaultComments'=>COMMENT_SET[1],
		],
		'sleepTimeDay'=>35,
		'sleepTimeNight'=>40,
	],
	3=>[
		'master'=>[
			'user'=>USER_SET['hkcoder'],
			'numberOfLikes'=> 30, 'allowComment'=>false, 'allowLike'=>true,
			'tagsDay'=>TAG_SET[2], 'tagsNight'=>TAG_SET[2],
			'defaultComments'=>COMMENT_SET[2],
		],
		'slave'=>[
			'user'=>USER_SET['dr.food.hk'],
			'numberOfLikes'=> 70, 'allowComment'=>true, 'allowLike'=>true, 
			'tagsDay'=>TAG_SET[3], 'tagsNight'=>TAG_SET[3],
			'defaultComments'=>COMMENT_SET[1],
		],
		'sleepTimeDay'=>35,
		'sleepTimeNight'=>40,
	],
	4=>[
		'master'=>[
			'user'=>USER_SET['fm.shot'],
			'numberOfLikes'=> 30, 'allowComment'=>false, 'allowLike'=>true,
			'tagsDay'=>TAG_SET[6], 'tagsNight'=>TAG_SET[6],
			'defaultComments'=>COMMENT_SET[3],
		],
		'slave'=>[
			'user'=>USER_SET['fmchan'],
			'numberOfLikes'=> 40, 'allowComment'=>true, 'allowLike'=>true,
			'tagsDay'=>TAG_SET[4], 'tagsNight'=>TAG_SET[4],
			'defaultComments'=>COMMENT_SET[0],
		],
		'sleepTimeDay'=>35,
		'sleepTimeNight'=>40,
	],
	5=>[
		'master'=>[
			'user'=>USER_SET['foodragonhk'],
			'numberOfLikes'=> 30, 'allowComment'=>false, 'allowLike'=>true,
			'tagsDay'=>TAG_SET[7], 'tagsNight'=>TAG_SET[7],
			'defaultComments'=>COMMENT_SET[3],
		],
		'slave'=>[
			'user'=>USER_SET['foodragonhk'],
			'numberOfLikes'=> 40, 'allowComment'=>false, 'allowLike'=>true,
			'tagsDay'=>TAG_SET[4], 'tagsNight'=>TAG_SET[4],
			'defaultComments'=>COMMENT_SET[0],
		],
		'sleepTimeDay'=>35,
		'sleepTimeNight'=>40,
	],
	6=>[
		'master'=>[
			'user'=>USER_SET['hkinvestor'],
			'numberOfLikes'=> 30, 'allowComment'=>false, 'allowLike'=>true,
			'tagsDay'=>TAG_SET[8], 'tagsNight'=>TAG_SET[8],
			'defaultComments'=>COMMENT_SET[0],
		],
		'slave'=>[
			'user'=>USER_SET['fmchan'],
			'numberOfLikes'=> 70, 'allowComment'=>false, 'allowLike'=>true,
			'tagsDay'=>TAG_SET[4], 'tagsNight'=>TAG_SET[4],
			'defaultComments'=>COMMENT_SET[0],
		],
		'sleepTimeDay'=>35,
		'sleepTimeNight'=>40,
	],
	7=>[
		'master'=>[
			'user'=>USER_SET['hea.eat'],
			'numberOfLikes'=> 30, 'allowComment'=>false, 'allowLike'=>true,
			'tagsDay'=>TAG_SET[5], 'tagsNight'=>TAG_SET[5],
			'defaultComments'=>COMMENT_SET[0],
		],
		'slave'=>[
			'user'=>USER_SET['fmchan'],
			'numberOfLikes'=> 70, 'allowComment'=>false, 'allowLike'=>true,
			'tagsDay'=>TAG_SET[4], 'tagsNight'=>TAG_SET[4],
			'defaultComments'=>COMMENT_SET[0],
		],
		'sleepTimeDay'=>35,
		'sleepTimeNight'=>40,
	],
]);

const MAX_ACCOUNT_LIKE = 5;

const IGNORE_OLD_POST = 5; //days
const SWITCH_COPY_COMMENT = 10;
const MIN_COMMENTS = 3;
const MAX_COMMENTS = 70;
const MAX_POST_LIKES = 300;
const MAX_USER_LIKES = 2;
const TIME_WAIT = 60;
const SWITCH_WAIT = 30;

const MAX_LOG_LINE = 4000;
const LOG_FOLDER = 'logs4like/';

const BAN_LIST = ['代購','美容','排毒','減肥','美甲','豐胸','買粉','约炮','裙','交友','飾物','染髮','性愛'];

const COMMENT_LIST = ["試","靚","食","吸引","份量","正","好","唔錯","抵","delicious","good","love","yummy"];

const GROUP_KEYWORD = 'foodie|互|group';
